<?php

/**
 * @file
 * Contains markaspot_confirm.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function markaspot_confirm_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the markaspot_confirm module.
    case 'help.page.markaspot_confirm':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Mark-a-Spot Confirm') . '</p>';
      return $output;

    default:
  }
}
