/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

function invertColor(hex, bw) {
  if (hex.indexOf('#') === 0) {
    hex = hex.slice(1);
  }

  if (hex.length === 3) {
    hex = hex[0] + hex[0] + hex[1] + hex[1] + hex[2] + hex[2];
  }

  if (hex.length !== 6) {
    throw new Error('Invalid HEX color.');
  }

  var r = parseInt(hex.slice(0, 2), 16),
      g = parseInt(hex.slice(2, 4), 16),
      b = parseInt(hex.slice(4, 6), 16);

  if (bw) {
    return r * 0.299 + g * 0.587 + b * 0.114 > 186 ? '#000000' : '#FFFFFF';
  }

  r = (255 - r).toString(16);
  g = (255 - g).toString(16);
  b = (255 - b).toString(16);
  return "#" + padZero(r) + padZero(g) + padZero(b);
}

function padZero(str, len) {
  len = len || 2;
  var zeros = new Array(len).join('0');
  return (zeros + str).slice(-len);
}

(function ($, Drupal, drupalSettings) {
  Drupal.Markaspot = {};
  Drupal.Markaspot.maps = [];
  var markerLayer;
  var scrolledMarker = [];
  var currentPath = drupalSettings.path.currentPath;
  currentPath = "".concat(currentPath);
  var masSettings = drupalSettings.mas;
  Drupal.behaviors.markaspot_map = {
    attach: function attach(context, settings) {
      Drupal.Markaspot.settings = masSettings;
      var mapSelector = $("#map");
      var center = [[masSettings.center_lat, masSettings.center_lng]];

      if (typeof mapSelector === 'undefined') {
        return;
      }

      var $serviceRequests = $(masSettings.nid_selector);
      $serviceRequests.hover(function () {
        var nid = this.dataset.historyNodeId;
        var $node = this;
        scrolledMarker.forEach(function (value) {
          if (value["nid"] == nid) {
            $node.classList.toggle("focus");
            Drupal.markaspot_map.showCircle(scrolledMarker[nid]);
          }
        });
      });
      mapSelector.once("markaspot_map").each(function () {
        Drupal.Markaspot.maps[0] = L.map("map", {
          fullscreenControl: true,
          scrollWheelZoom: !L.Browser.mobile,
          minZoom: 12,
          maxZoom: 18,
          dragging: !L.Browser.mobile,
          zoom: masSettings.zoom_initial
        });
        var tileLayer;
        var map = Drupal.Markaspot.maps[0];

        if (masSettings.map_type === "0") {
          var gl = L.mapboxGL({
            accessToken: masSettings.mapbox_token,
            style: masSettings.mapbox_style,
            center: center
          }).addTo(map);
        }

        if (masSettings.map_type === "1") {
          if (masSettings.wms_service == '') {
            tileLayer = L.tileLayer(masSettings.osm_custom_tile_url, {
              edgeBufferTiles: 1
            });
          } else {
            tileLayer = L.tileLayer.wms(masSettings.wms_service, {
              layers: masSettings.wms_layer,
              edgeBufferTiles: 1
            });
          }

          map.addLayer(tileLayer);
        }

        map.attributionControl.addAttribution(masSettings.osm_custom_attribution);
        markerLayer = L.markerClusterGroup({
          maxClusterRadius: 20
        });
        map.addLayer(markerLayer);
        localStorage.setItem("storedNids", JSON.stringify(""));
      });
      var storedNids = JSON.parse(localStorage.getItem("storedNids"));
      var nids = Drupal.markaspot_map.getNids(masSettings.nid_selector);
      Drupal.markaspot_map.setDefaults(masSettings);

      if (JSON.stringify(nids) !== JSON.stringify(storedNids)) {
        localStorage.setItem("storedNids", JSON.stringify(nids));

        if (typeof markerLayer !== "undefined") {
          markerLayer.clearLayers();
          Drupal.markaspot_map.load(function (data) {
            Drupal.markaspot_map.showData(data);
            markerLayer.eachLayer(function (layer) {
              var nid = layer.options.nid;
              scrolledMarker[nid] = {
                latlng: layer.getLatLng(),
                nid: layer.options.nid,
                color: layer.options.color
              };
            });
          }, nids);
        }
      }

      $('.view-content').once('markaspot_map').each(function () {
        $serviceRequests.each(function () {
          new Waypoint({
            element: this,
            handler: function handler(direction) {
              var nid = this.element.dataset.historyNodeId;

              if (typeof scrolledMarker[nid] !== "undefined") {
                Drupal.markaspot_map.showCircle(scrolledMarker[nid]);
                this.element.classList.add("focus");
              } else {
                this.element.classList.add("no-location");
                Drupal.Markaspot.maps[0].setView([masSettings.center_lat, masSettings.center_lng], 10);
                return;
              }

              if (direction === "up") {
                this.element.classList.remove("focus");
              }
            },
            offset: "40%"
          });
        });
      });
    }
  };
  Drupal.markaspot_map = {
    setDefaults: function setDefaults() {
      var defaultCenter = new L.LatLng(masSettings.center_lat, masSettings.center_lng);
      var map = Drupal.Markaspot.maps[0];

      if (typeof map !== "undefined") {
        map.setView(defaultCenter, masSettings.zoom_initial);
      }
    },
    showHeatMap: function showHeatMap() {
      var map = Drupal.Markaspot.maps[0];
      Drupal.markaspot_map.createGeoJsonTimedLayer(map);
      Drupal.Markaspot.heatMapLayer = Drupal.markaspot_map.createHeatMapLayer();
      Drupal.Markaspot.heatMapLayer.addTo(map);
    },
    hideHeatMap: function hideHeatMap() {
      var map = Drupal.Markaspot.maps[0];
      map.removeLayer(Drupal.Markaspot.heatMapLayer);
    },
    showTimeControl: function showTimeControl() {
      var map = Drupal.Markaspot.maps[0];

      var getInterval = function getInterval(request) {
        return {
          start: request.properties.time,
          end: request.properties.updated
        };
      };

      var data = Drupal.markaspot_map.createGeoJsonLayer(map);
      var timeline = L.timeline(data, {
        getInterval: getInterval,
        pointToLayer: function pointToLayer(data, latlng) {
          return L.circleMarker(latlng, {
            radius: 10,
            color: "#000",
            fillColor: "#000"
          });
        }
      });
      Drupal.markaspot_map.timelineControl = L.timelineSliderControl({
        formatOutput: function formatOutput(date) {
          var dateObj = new Date(date);
          var yyyy = dateObj.getFullYear();
          var mm = String(dateObj.getMonth() + 1).padStart(2, '0');
          var dd = String(dateObj.getDate()).padStart(2, '0');
          return "".concat(dd, ".").concat(mm, ".").concat(yyyy);
        }
      });
      var timelineControl = Drupal.markaspot_map.timelineControl;
      timelineControl.addTo(map);
      timelineControl.addTimelines(timeline);
      timeline.addTo(map);
    },
    hideTimeControl: function hideTimeControl() {
      var map = Drupal.Markaspot.maps[0];
      map.removeControl(Drupal.markaspot_map.timelineControl);
    },
    showCircle: function showCircle(marker) {
      var markerId = marker.nid;

      if (_typeof(markerId) === undefined || markerId === this.marker) {
        return;
      }

      this.marker = markerId;
      var map = Drupal.Markaspot.maps[0];
      var mapDefaultZoom = masSettings.zoom_initial;

      if (typeof marker === "undefined") {
        return;
      }

      var color = marker.color;
      var circle = L.circle(marker.latlng, 3600 / mapDefaultZoom, {
        color: color,
        className: "auto_hide",
        weight: 1,
        fillColor: color,
        fillOpacity: 0.2
      }).addTo(map);
      map.flyTo(marker.latlng, mapDefaultZoom, {
        duration: 0.8
      });
      map.invalidateSize();
      setTimeout(function () {
        $(".auto_hide").animate({
          opacity: 0
        }, 500, function () {
          map.removeLayer(circle);
        });
      }, 1000);
      return circle;
    },
    createGeoJson: function createGeoJson(data) {
      if (typeof data !== "undefined") {
        var feature;
        var features = [];

        if (data.length) {
          for (var i = 0; i < data.length; i++) {
            var time = Math.floor(new Date(data[i].requested_datetime).getTime());
            feature = {
              type: "Feature",
              properties: {
                time: time,
                updated: time + 86400000 * 2
              },
              geometry: {
                type: "Point",
                coordinates: [data[i].long, data[i].lat]
              }
            };
            features.push(feature);
          }
        }

        return {
          type: "FeatureCollection",
          metadata: {
            count: data.length
          },
          features: features
        };
      }
    },
    retrieveStaticData: function retrieveStaticData() {
      return Drupal.markaspot_static_json.getData();
    },
    createGeoJsonLayer: function createGeoJsonLayer(map) {
      var data = this.retrieveStaticData();
      var geoJson = this.createGeoJson(data);
      return geoJson;
    },
    createGeoJsonTimedLayer: function createGeoJsonTimedLayer() {
      var geoJsonLayer = Drupal.markaspot_map.createGeoJsonLayer();
      return geoJsonLayer;
    },
    transformGeoJson2heat: function transformGeoJson2heat(geojson, intensity) {
      return geojson.features.map(function (feature) {
        return [feature.geometry.coordinates[1], feature.geometry.coordinates[0], intensity];
      });
    },
    updateHeatMapLayer: function updateHeatMapLayer(heatPoint) {
      var heatLayer = {};
      var map = Drupal.Markaspot.maps[0];
      map.eachLayer(function (layer) {
        if (layer.id === "heatTimedLayer") {
          heatLayer = layer;
        }
      });
      heatLayer.addLatLng(heatPoint);
    },
    createHeatMapLayer: function createHeatMapLayer() {
      var data = this.retrieveStaticData();
      var geoJson = this.createGeoJson(data);
      var heatPoints = this.transformGeoJson2heat(geoJson, 4);
      return new L.HeatLayer(heatPoints, {
        blur: 25,
        maxZoom: 17
      });
    },
    hideMarkers: function hideMarkers() {
      Drupal.Markaspot.maps[0].closePopup();
      Drupal.Markaspot.maps[0].removeLayer(markerLayer);
    },
    showMarkers: function showMarkers() {
      Drupal.Markaspot.maps[0].addLayer(markerLayer);
    },
    markerClickFn: function markerClickFn(marker, nid) {
      return function markerClick() {
        var map = Drupal.Markaspot.maps[0];
        var currentZoom = map.getZoom();
        var fullscreen = map.isFullscreen();
        var target = $("article[data - history - node - id = ".concat(nid, "]"));

        if (target.length && fullscreen === false && currentPath !== "/home") {
          map.setZoom(currentZoom + 2);
          $("html, body").stop().animate({
            scrollTop: target.offset().top - 250
          }, 1000);
        } else if (target.length && fullscreen === true || currentPath === "/home") {
          var html = target.find("h2").html();
          marker.bindPopup(html);
        }
      };
    },
    showData: function showData(dataset) {
      var _this = this;

      if (dataset.status === 404) {
        return false;
      }

      $.each(dataset, function (serviceRequests, request) {
        var categoryColor = request.extended_attributes.markaspot.category_hex;
        var awesomeIcon = request.extended_attributes.markaspot.category_icon;
        var nid = request.extended_attributes.markaspot.nid;
        var latlon = new L.LatLng(request.lat, request.long);
        var masSettings = drupalSettings.mas;
        var center = {};
        var pos = {};
        pos.long = Number(request.long.toFixed(3));
        pos.lat = Number(request.lat.toFixed(3));
        center.lat = parseFloat(masSettings.center_lat).toFixed(3);
        center.lng = parseFloat(masSettings.center_lng).toFixed(3);

        if (center.lat == pos.lat && center.lng == pos.long) {
          return;
        }

        var iconSettings = {
          mapIconUrl: masSettings.marker
        };
        iconSettings.mapIconColor = invertColor(categoryColor, 1);
        iconSettings.mapIconFill = categoryColor;
        iconSettings.mapIconSymbol = awesomeIcon;
        var svgIcon = L.Util.template(iconSettings.mapIconUrl, iconSettings);
        var icon = L.divIcon({
          html: svgIcon,
          iconAnchor: eval(masSettings.iconAnchor)
        });
        var marker = new L.Marker(latlon, {
          icon: icon,
          nid: nid
        });
        marker.on("click", _this.markerClickFn(marker, nid));
        markerLayer.addLayer(marker);
      });
      var size = markerLayer.getLayers().length;

      if (size >= 1) {
        Drupal.Markaspot.maps[0].fitBounds(markerLayer.getBounds(), {
          padding: [50, 50]
        });
      } else {
        Drupal.markaspot_map.setDefaults();
      }

      return markerLayer;
    },
    load: function load(getData, nids) {
      var url = drupalSettings.path.baseUrl;
      url = "".concat(url, "georeport/v2/requests.json?extensions=true&nids=").concat(nids);
      return $.getJSON(url).done(function (data) {
        getData(data);
      }).fail(function (data) {
        getData(data);
      });
    },
    getNids: function getNids(selector) {
      var serviceRequests = $(selector);
      var nids = [];

      for (var i = 0, length = serviceRequests.length; i < length; i++) {
        var element = serviceRequests[i];
        nids.push(element.getAttribute("data-history-node-id"));
      }

      return nids;
    }
  };
})(jQuery, Drupal, drupalSettings);