<?php

/**
 * @file
 * Contains markaspot_feedback.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function markaspot_feedback_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the markaspot_feedback module.
    case 'help.page.markaspot_feedback':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Mark-a-Spot Feedback') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function markaspot_feedback_cron() {
  // We access our configuration.
  $config = \Drupal::config('markaspot_feedback.settings');
  
  // Default to an hourly interval. Of course, cron has to be running at least
  // hourly for this to work.
  $interval = $config->get('interval');
  $interval = !empty($interval) ? $interval : 3600;

  // We usually don't want to act every time cron runs (which could be every
  // minute) so keep a time for the next run in the site state.
  $next_execution = \Drupal::state()
    ->get('markaspot_feedback.next_execution', 0);
  if (\Drupal::time()->getRequestTime() >= $next_execution && $config->get('enable') == 1) {

    // Get all nodes eligible for feedback from the service.
    $feedbackSendable = \Drupal::service('markaspot_feedback.feedback')->load();
    $count = 0;

    // Get the queue for the feedback worker.
    $queue = \Drupal::queue('markaspot_feedback_queue_worker');
    
    foreach ($feedbackSendable as $node) {
      // Queue the node for processing.
      $queue->createItem(['nid' => $node->id()]);
      $count++;
    }

    \Drupal::logger('markaspot_feedback')->notice('Enqueued @count nodes for feedback emails.', ['@count' => $count]);

    // Set the next execution time.
    \Drupal::state()
      ->set('markaspot_feedback.next_execution', \Drupal::time()->getRequestTime() + $interval);
  }
}


function markaspot_feedback_getBody($node, $mailText) {

  $data = [
    'node' => $node,
  ];
  $token_service = \Drupal::token();
  // Replace the token for subject.
  return $token_service->replace($mailText, $data);
}






/**
 * Implements hook_mail().
 */

function markaspot_feedback_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
  );

  switch ($key) {
    case 'resubmit_request':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('Your feedback for: @title', array('@title' => $params['node_title']), $options);
      $message['body'][] = $params['message'];
      break;
  }
}
