<?php

/**
 * Implements hook_migration_plugins_alter().
 */
function markaspot_default_content_migration_plugins_alter(&$definitions) {
  $path = \Drupal::service('extension.list.module')->getPath('markaspot_default_content');

  $migrations = [
    'markaspot_migrate_default_content_group_jurisdiction',
    'markaspot_migrate_default_content_group_organisation',
    'markaspot_migrate_default_content_page',
    'markaspot_migrate_default_content_boilerplate',
    'markaspot_migrate_default_content_service_provider',
    'markaspot_migrate_default_content_service_status',
    'markaspot_migrate_default_content_service_category',
    'markaspot_migrate_default_content_block',
  ];

  foreach ($migrations as $migration_id) {
    if (isset($definitions[$migration_id]['source']['path'])) {
      $definitions[$migration_id]['source']['path'] = $path . $definitions[$migration_id]['source']['path'];
    }
  }
}
