<?php

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 *
 * attach js and html attributes to dynamically add taxonony term description
 * to SHS widget
 *
 * currently only applicable for fields with cardinality of 1
 */
function markaspot_shstweak_field_widget_options_shs_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  $items = $context['items'];
  $widget = $context['widget'];
  if ($items instanceof \Drupal\Core\Field\EntityReferenceFieldItemList && $widget instanceof \Drupal\shs\Plugin\Field\FieldWidget\OptionsShsWidget) {
    if ($items->getFieldDefinition()->getFieldStorageDefinition()->getCardinality() === 1) {
      if ($widget->getThirdPartySetting('markaspot_shstweak', 'add_description')) {
        $element['#attached']['library'][] = 'markaspot_shstweak/shstweak';
        $element['#attributes']['class'][] = 'shs-description-enabled';
        $element['#attributes']['data-shs-last-child'] = (int) $widget->getThirdPartySetting('markaspot_shstweak', 'only_last_child');
        // This is html placeholder for the taxonomy term description
        $element['#suffix'] = '<div class="taxonomy-description ' . $items->getName() . '"></div>';
      }
    }
  }
}

/**
 * Implements hook_field_widget_third_party_settings_form().
 *
 * add third party settings for SHS widget
 */
function markaspot_shstweak_field_widget_third_party_settings_form(\Drupal\Core\Field\WidgetInterface $plugin, \Drupal\Core\Field\FieldDefinitionInterface $field_definition, $form_mode, array $form, \Drupal\Core\Form\FormStateInterface $form_state) {
  if ($plugin->getPluginId() == 'options_shs' && $field_definition->getFieldStorageDefinition()->getCardinality() === 1) {
    $element = [];
    $element['add_description'] = [
      '#type' => 'checkbox',
      '#title' => t('Add taxonomy term description to SHS widget'),
      '#default_value' => $plugin->getThirdPartySetting('markaspot_shstweak', 'add_description')
    ];
    $element['only_last_child'] = [
      '#type' => 'checkbox',
      '#title' => t('Add taxonomy term description only to last childs'),
      '#default_value' => $plugin->getThirdPartySetting('markaspot_shstweak', 'only_last_child'),
      '#states' => [
        'visible' => [
          ':input[name="fields['.$field_definition->getName().'][settings_edit_form][third_party_settings][markaspot_shstweak][add_description]"]' => [
            'checked' => TRUE,
          ]
        ]
      ]
    ];
    return $element;
  }
}

/**
 * Implements hook_field_widget_settings_summary_alter().
 *
 * add summary for SHS widget third party settings
 */
function markaspot_shstweak_field_widget_settings_summary_alter(array &$summary, array $context) {
  if ($context['widget'] instanceof \Drupal\Core\Field\WidgetInterface && $context['widget']->getPluginId() === 'options_shs') {
    if ($context['widget']->getThirdPartySetting('markaspot_shstweak', 'add_description')) {
      if ($context['field_definition'] instanceof \Drupal\field\Entity\FieldConfig && $context['field_definition']->getFieldStorageDefinition()->getCardinality() !== 1) {
        $summary[] = t('Taxonomy term description settings not applicable.');
      }
      else {
        $summary[] = t('Add taxonomy term description');
        if ($context['widget']->getThirdPartySetting('markaspot_shstweak', 'only_last_child')) {
          $summary[] = t('.. to last child only.');
        }
      }
    }
  }
}


