/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  Drupal.mas_olivero = {};
  var body = document.querySelector('body');

  if (body.classList.contains('path-frontpage') == false && body.classList.contains('page-node-type-page') == false) {
    var _map = document.getElementById('#map');

    var stickyElement = document.getElementsByClassName('map-request-block');

    if (stickyElement.length) {
      Drupal.sticky = new Waypoint.Sticky({
        element: stickyElement[0],
        wrapper: '<div class="sticky-wrapper waypoint" />'
      });
    }
  }

  var heatMapButton = document.querySelector('.heatmap a');

  if (heatMapButton !== null) {
    heatMapButton.onclick = function () {
      this.classList.toggle('is-active');

      if (this.classList.contains('is-active')) {
        Drupal.markaspot_map.showHeatMap();
      } else {
        Drupal.markaspot_map.hideHeatMap();
      }
    };
  }

  var timeControlButton = document.querySelector('.time-control a');

  if (timeControlButton !== null) {
    timeControlButton.onclick = function () {
      this.classList.toggle('is-active');

      if (this.classList.contains('is-active')) {
        Drupal.markaspot_map.showTimeControl();
      } else {
        Drupal.markaspot_map.hideTimeControl();
      }
    };
  }

  var config = {
    attributes: true,
    childList: false,
    characterData: false,
    subtree: false
  };
  var map = document.getElementById('map');

  if (map !== null) {
    var observer = new MutationObserver(function (mutations) {
      return Drupal.Markaspot.maps[0].invalidateSize();
    });
    observer.observe(map, config);
  }
})(Drupal);