/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal) {
  Drupal.mas_olivero = {};
  Drupal.behaviors.mas_olivero_navigation = {
    attach: function attach(context) {
      var stickyHeaderState = localStorage.getItem('Drupal.olivero.stickyHeaderState');
      var body = context.querySelector('body');

      if (body.classList.contains('path-frontpage') == false && body.classList.contains('page-node-type-page') == false) {
        var map = context.querySelector('[data-drupal-selector="map-request-block"]');
        console.log(map);
        Drupal.sticky = new Waypoint.Sticky({
          element: map,
          wrapper: '<div class="sticky-wrapper waypoint" />'
        });

        if (JSON.parse(stickyHeaderState).value == true) {
          map.classList.add("stuck-nav");
        }
      }
    }
  };
  var observer = new MutationObserver(function (mutations) {
    var startBlock = document.getElementById('block-markaspotfrontaction');
    var fieldsetMap = document.getElementById('geolocation-nominatim-map');
    mutations.forEach(function (mutation) {
      if (mutation.type === "attributes" && mutation.target.className.indexOf('overlay-active') != -1) {
        fieldsetMap ? fieldsetMap.style.display = 'none' : false;
        startBlock ? startBlock.style.display = 'none' : false;
      } else {
        fieldsetMap ? fieldsetMap.style.display = 'block' : false;
        startBlock ? startBlock.style.display = 'block' : false;
      }
    });
  });
  var heatMapButton = document.querySelector('.heatmap a');

  if (heatMapButton !== null) {
    heatMapButton.onclick = function () {
      this.classList.toggle('is-active');

      if (this.classList.contains('is-active')) {
        Drupal.markaspot_map.showHeatMap();
      } else {
        Drupal.markaspot_map.hideHeatMap();
      }
    };
  }

  var timeControlButton = document.querySelector('.time-control a');

  if (timeControlButton !== null) {
    timeControlButton.onclick = function () {
      this.classList.toggle('is-active');

      if (this.classList.contains('is-active')) {
        Drupal.markaspot_map.showTimeControl();
      } else {
        Drupal.markaspot_map.hideTimeControl();
      }
    };
  }

  var config = {
    attributes: true,
    childList: false,
    characterData: false,
    subtree: false
  };
})(Drupal);