/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.mas_olivero = {
    attach: function attach(context) {
      var stickyHeaderState = localStorage.getItem('Drupal.olivero.stickyHeaderState');

      if (!context.querySelector('body')) {
        return;
      }

      if (context.querySelector('.path-requests')) {
        var _map = context.querySelector('[data-drupal-selector="map-request-block"]');

        Drupal.sticky = new Waypoint.Sticky({
          element: _map,
          wrapper: '<div class="sticky-wrapper waypoint" />'
        });

        if (JSON.parse(stickyHeaderState).value == true) {
          _map.classList.add("stuck-nav");
        }
      }
    }
  };
  var observer = new MutationObserver(function (mutations) {
    var startBlock = document.getElementById('block-markaspotfrontaction');
    var fieldsetMap = document.getElementById('geolocation-nominatim-map');
    mutations.forEach(function (mutation) {
      if (mutation.type === "attributes" && mutation.target.className.indexOf('overlay-active') != -1) {
        fieldsetMap ? fieldsetMap.style.display = 'none' : false;
        startBlock ? startBlock.style.display = 'none' : false;
      } else {
        fieldsetMap ? fieldsetMap.style.display = 'block' : false;
        startBlock ? startBlock.style.display = 'block' : false;
      }
    });
  });
  var heatMapButton = document.querySelector('.heatmap a');

  if (heatMapButton !== null) {
    heatMapButton.onclick = function () {
      this.classList.toggle('is-active');

      if (this.classList.contains('is-active')) {
        Drupal.markaspot_map.showHeatMap();
      } else {
        Drupal.markaspot_map.hideHeatMap();
      }
    };
  }

  var timeControlButton = document.querySelector('.time-control a');

  if (timeControlButton !== null) {
    timeControlButton.onclick = function () {
      this.classList.toggle('is-active');

      if (this.classList.contains('is-active')) {
        Drupal.markaspot_map.showTimeControl();
      } else {
        Drupal.markaspot_map.hideTimeControl();
      }
    };
  }

  var config = {
    attributes: true,
    childList: false,
    characterData: false,
    subtree: false
  };
  var map = document.getElementById('map');

  if (map !== null) {
    var _observer = new MutationObserver(function (mutations) {
      return Drupal.Markaspot.maps[0].invalidateSize();
    });

    _observer.observe(map, config);
  }
})(jQuery, Drupal);